insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("David ","Reese","Phoenix","AZ","Reese, Dav%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Jerry ","Hirsch","Phoenix","AZ","Hirsch, Jer%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Bonnie","Fujiii","","","Fujiii, Bon%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Weezie","Reese","Phoenix","AZ","Reese, Wee%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Franklin","Arthur","Piedmont","CA","Arthur, Fra%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("William","Battle","Los Altos","CA","Battle, Wil%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Nicolette","Beck","San Francisco","CA","Beck, Nic%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Art","Berliner","Berkeley","CA","Berliner, Art%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Bob","Burnett","Occidental","CA","Burnett, Bob%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Jim","Chu","San Francisco","CA","Chu, Jim%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Tony","Crabb","Healdsburg","CA","Crabb, Ton%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Alan","Davis","San Francisco","CA","Davis, Ala%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Tim","Disney","Los Angeles","CA","Disney, Tim%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Jerry","Fiddler","Berkeley","CA","Fiddler, Jer%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Mary","Ford","Stinson Beach","CA","Ford, Mar%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Lloys","Fretas","Los Angeles","CA","Fretas, Llo%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Anne","Germanacos","San Francisco","CA","Germanacos, Ann%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Phil","Jensen","Sebastopol","CA","Jensen, Phi%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Jean","Kaplan","Santa Barbara","CA","Kaplan, Jea%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Maureen","Kennedy","Inverness","CA","Kennedy, Mau%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Suzanne","Lerner","Hawthorne","CA","Lerner, Suz%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("John","O'Farrell","Menlo Park","CA","O'Farrell, Joh%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Frank","Patitucci","Pleasanton","CA","Patitucci, Fra%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Drew","Pomerance","Tarzana","CA","Pomerance, Dre%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Susan","Pritzker","San Francisco","CA","Pritzker, Sus%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Dorine","Real","San Francisco","CA","Real, Dor%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Paul","Rosenstiel","San Francisco","CA","Rosenstiel, Pau%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Sandor ","Straus","Lafayette","CA","Straus, San%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Diane","Trombetta","Los Gatos","CA","Trombetta, Dia%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Roy","Ulrich","Berkeley","CA","Ulrich, Roy%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Dale","Walker","San Francisco","CA","Walker, Dal%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Carol","Winograd","SF","CA","Winograd, Car%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Carol","Winograd","Stanford","CA","Winograd, Car%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Bennet","Yee","Mountain View","CA","Yee, Ben%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("David","Altschul","Encino","CA","Altschul, Dav%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Jackie","Boberg","Saratoga","CA","Boberg, Jac%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Richard","Boberg","Saratoga","CA","Boberg, Ric%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Michael ","Burke","Redondo Beach","CA","Burke, Mic%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Stephen","English","Pasadena","CA","English, Ste%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Andrew","Faulk","San Francisco","CA","Faulk, And%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Charlie","Fink","Glendale","CA","Fink, Cha%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Richard","Foos","Los Angeles","CA","Foos, Ric%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Ellyn","Gelson","Encino","CA","Gelson, Ell%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Kelly ","Greenwood (married to Jules)","San Francisco","CA","Greenwood (married to Jules), Kel%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Frank","Jernigan","San Francisco","CA","Jernigan, Fra%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Dick","Mader","Glendale","CA","Mader, Dic%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Jules","Maltz","San Francisco","CA","Maltz, Jul%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Diane","Meyer Simon","Santa Barbara","CA","Meyer Simon, Dia%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Alison","Morgan","Pasadena","CA","Morgan, Ali%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Molly","Munger","Pasadena","CA","Munger, Mol%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Sophie","Ragir","Venice ","CA","Ragir, Sop%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("John","Reese","Playa Vista","CA","Reese, Joh%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("T.M.","Scruggs Jr.","Berkeley","CA","Scruggs Jr., T.M%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Spencer","Sherman","Sebastopol","CA","Sherman, Spe%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Stephen","Silberstein","Belvedere Tiburon","CA","Silberstein, Ste%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Barbara","Simons","San Francisco","CA","Simons, Bar%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Karen","Stewart","Vista","CA","Stewart, Kar%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Faye ","Straus","Lafayette","CA","Straus, Fay%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Arthur","Strauss","Irvine","CA","Strauss, Art%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("David","Watson","Oakland","CA","Watson, Dav%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Vinitha","Watson","Oakland","CA","Watson, Vin%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Terry","Winograd","Stanford","CA","Winograd, Ter%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Amy","Ziering","Los Angeles","CA","Ziering, Amy%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("George","Zimmer","Fremont","CA","Zimmer, Geo%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Merle","Chambers","Denver","CO","Chambers, Mer%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Cynda","Collins-Arsenault","Superior","CO","Collins-Arsenault, Cyn%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Ron","Guillot","Denver","CO","Guillot, Ron%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("James","Iacino","Ridgeway","CO","Iacino, Jam%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Blake","Jones","Boulder","CO","Jones, Bla%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Nancy","Reichman","Denver","CO","Reichman, Nan%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Linda","Shoemaker","Boulder","CO","Shoemaker, Lin%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Joe","Zimlich","Fort Collins","CO","Zimlich, Joe%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Pat","Stryker","Fort Collins","CO","Stryker, Pat%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Joanne","Goldblum","Branford","CT","Goldblum, Joa%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("John","Driscoll","Stamford","CT","Driscoll, Joh%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Ken","Grossinger","Washington","DC","Grossinger, Ken%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("James","Colen","Davie","FL","Colen, Jam%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Becky","Gochman","Palm Beach","FL","Gochman, Bec%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Robert","Goldschmidt","University Park","FL","Goldschmidt, Rob%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Kim","Hoover","Miami","FL","Hoover, Kim%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Diane","Isenberg","Palm Beach","FL","Isenberg, Dia%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("David","Nixon","St Pete Beach","FL","Nixon, Dav%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Stuart","Opotowsky","West Palm Beach","FL","Opotowsky, Stu%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Gary","Passon","Kihei","HI","Passon, Gar%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Susan","Kubiak","Dover ","ID","Kubiak, Sus%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Bill","Parks","Moscow","ID","Parks, Bil%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Laurie ","Bergner","Normal","IL","Bergner, Lau%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Thomas","McDougal","Chicago","IL","McDougal, Tho%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Michael","Pine","Evanston","IL","Pine, Mic%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Michael","Rothman","Chicago","IL","Rothman, Mic%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Ray","Bergner","Normal","IL","Bergner, Ray%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Eric","Draut","Arlington Heights","IL","Draut, Eri%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Richard","Rice","Skokie","IL","Rice, Ric%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Bonnie","Rothman","Chicago","IL","Rothman, Bon%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Thomas","Curran","Prarie Village","KS","Curran, Tho%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Geoff","Coventry","Overland Park","KS","Coventry, Geo%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Eleanor","Bingham Miller","Goshen","KY","Bingham Miller, Ele%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Woody","Kaplan","Boston","MA","Kaplan, Woo%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Persis","Levy","Arlington ","MA","Levy, Per%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Ken","Olum","Sharon","MA","Olum, Ken%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Peg","Primak","Waltham","MA","Primak, Peg%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Amelie","Ratliff","Jamaica Plain","MA","Ratliff, Ame%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Naomi","Aberly","Boston","MA","Aberly, Nao%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Alecia","Carey","Boston","MA","Carey, Ale%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Chuck","Collins","Boston","MA","Collins, Chu%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Eric","Klose","Boston","MA","Klose, Eri%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Ian","Simmons","Boston","MA","Simmons, Ian%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Sidney","Topol","Boston","MA","Topol, Sid%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Scott","Nash","Chevy Chase","MD","Nash, Sco%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Suzanne","Nash","Chevy Chase","MD","Nash, Suz%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Michael ","Lambert","Portland","ME","Lambert, Mic%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Ron ","Carter","Columbia","MO","Carter, Ron%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Barry","Segal","Warren","NJ","Segal, Bar%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Martin","Segal","Warren","NJ","Segal, Mar%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Andrew","Ellis","","NJ","Ellis, And%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Eric","Schoenberg","Franklin Lakes","NJ","Schoenberg, Eri%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Patricia","Foschi","Sante Fe","NM","Foschi, Pat%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Marc","Baum","New York","NY","Baum, Mar%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Lawrence","Benenson","New York","NY","Benenson, Law%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Jill","Braufman","New York","NY","Braufman, Jil%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Dana","Bronfman","New York","NY","Bronfman, Dan%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Abigail","Disney","New York","NY","Disney, Abi%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Molly","Gochman","New York","NY","Gochman, Mol%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Bill","Janeway","New York","NY","Janeway, Bil%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Lawanna","Kimbro","New York","NY","Kimbro, Law%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Stephanie","Low","New York","NY","Low, Ste%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Patricia","Martone","New York","NY","Martone, Pat%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Marie","McKellar","Dobbs Ferry","NY","McKellar, Mar%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Michael","Nash","New York","NY","Nash, Mic%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Morris","Pearl","New York","NY","Pearl, Mor%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Claire","Silberman","Brooklyn ","NY","Silberman, Cla%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Daniel","Simon","New York","NY","Simon, Dan%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("James ","Simon","New York","NY","Simon, Jam%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Andrew","Tobias","New York","NY","Tobias, And%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Diana","Wege","New York","NY","Wege, Dia%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Peter","Weinberger","Syosset","NY","Weinberger, Pet%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Allison","Barlow","New York","NY","Barlow, All%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Anna Marie ","Cotter","New York","NY","Cotter, Ann%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Rick","Feldman","New York","NY","Feldman, Ric%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Jeffrey","Gural","New York","NY","Gural, Jef%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Anne","Hess","New York","NY","Hess, Ann%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Michael","Hirschorn","New York","NY","Hirschorn, Mic%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Craig","Kaplan","New York","NY","Kaplan, Cra%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Robbie","Kaplan","New York","NY","Kaplan, Rob%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("David","Ledy","New York","NY","Ledy, Dav%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("James","Mai","New York","NY","Mai, Jam%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Rebecca","Mai","New York","NY","Mai, Reb%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Vincent","Mai","Port Washington","NY","Mai, Vin%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Clare","McLaughlin","New York","NY","McLaughlin, Cla%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Terry","Meehan","New York","NY","Meehan, Ter%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Karen","Mehiel","New York","NY","Mehiel, Kar%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Dennis","Mehiel","New York","NY","Mehiel, Den%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("David","Mitnick","New York","NY","Mitnick, Dav%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Barbara","Pearl","New York","NY","Pearl, Bar%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Great Neck","Richman","New York","NY","Richman, Gre%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Chloe","Shanklin","New York","NY","Shanklin, Chl%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Angie","Wang","New York","NY","Wang, Ang%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Susan","Yost","Columbus","OH","Yost, Sus%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Kristin","Luck","Bend","OR","Luck, Kri%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Wendy","Li","Chester Springs","PA","Li, Wen%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Stephen","Segal","Philadelphia","PA","Segal, Ste%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Ritchie","Tabachnick","Ligonier","PA","Tabachnick, Rit%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Scott","Wallace","Doylestown","PA","Wallace, Sco%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Daniel","Berger","","PA","Berger, Dan%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Robert","Haines","Quakertown","PA","Haines, Rob%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Christy","Wallace","Doylestown","PA","Wallace, Chr%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Henry ","Thorne","Sewickley ","PA ","Thorne, Hen%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("John","Deane","Nashville","TN","Deane, Joh%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Stephen","Prince","Brentwood","TN","Prince, Ste%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Ted","LaRoche","Murfreesboro","TN","LaRoche, Ted%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Katy Drake","Bettner","McKinney","TX","Bettner, Kat%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Paul","Bettner","McKinney","TX","Bettner, Pau%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Joshua","Kanter","Sandy","UT","Kanter, Jos%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Art","Lipson","Salt Lake City","UT","Lipson, Art%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Jonathan","Ruga","Salt Lake City","UT","Ruga, Jon%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Catherine","Kanter","Sandy","UT","Kanter, Cat%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Rochelle","Kaplan","Salt Lake City","UT","Kaplan, Roc%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("John","Netto","Salt Lake City","UT","Netto, Joh%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Scott","Young","Salt Lake City","UT","Young, Sco%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Pierre","Hollis","Stafford","VA","Hollis, Pie%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Rachel","Hottendorf","Vienna","VA","Hottendorf, Rac%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Gabby","Jacoby","McLean","VA","Jacoby, Gab%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Jodie","Rubenstein","Alexandria","VA","Rubenstein, Jod%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Ross","Waller","Lexington","VA","Waller, Ros%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Donna","Carpenter","Burlington","VT","Carpenter, Don%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Donna","Carpenter","Burlington","VT","Carpenter, Don%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Patricia","Atkinson","Kirkland","WA","Atkinson, Pat%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Brian","Boland","Bellevue","WA","Boland, Bri%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Phyllis","Hatfield","Seattle","WA","Hatfield, Phy%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Becky","Liebman","Olympia","WA","Liebman, Bec%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Judy","Pigott","Seattle","WA","Pigott, Jud%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Daniel","Price","Seattle","WA","Price, Dan%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Douglas","Smith","Seattle","WA","Smith, Dou%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Will","Arora","Clyde Hill","WA","Arora, Wil%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Alida","Latham","Seattle","WA","Latham, Ali%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Albert and Bessie","Warner","Seattle ","WA","Warner, Alb%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Michael","Mader","La Crosse","WI","Mader, Mic%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Sage","Weil","Madison","WI","Weil, Sag%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Michael","Mader","La Crosse","WI","Mader, Mic%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Will","Carter","Culloden","WV","Carter, Wil%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Marguerite","Snowdon","Wilson","WY","Snowdon, Mar%",0,1,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Erica","Payne","","","Payne, Eri%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Olivia ","Redmond (asst to B.Gochman)","","","Redmond (asst to B.Gochman), Oli%",1,0,1);
insert into ngp_contacts (first_name, last_name, city, state, match_name, priv, pub, mem) values ("Joanne","Schneider","","","Schneider, Joa%",1,0,1);
